### ISSUE TITLE
<ug> anstatt <ul>

### ISSUE THREAD

**Issue by niWisco** [nicozillaaa/Uebung_1#1]
`<ug>` für ungeordnete Liste ist mir neu.. würde mich interessieren wo du es her hast :D könnte auf anhieb nicht mal etwas dazu finden.

**Comment by nicozillaaa** [comment]
ganz ehrlich ... ich dachte ich hätte mir das so aus deiner Präsentation gemerkt und da in der Webansicht auch die ungeordnete Liste angezeigt wurde, dachte ich das wäre richtig :D ich ändere das nachher ^^
